version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.digitalocean.com/clutchbids-registry/scraper-openlane-price-updater:latest
    container_name: scraper-openlane-price-updater